/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTeamRouteRouteImport } from './routes/admin/team/route'
import { Route as AdminPodcastRouteRouteImport } from './routes/admin/podcast/route'
import { Route as AdminJournalRouteRouteImport } from './routes/admin/journal/route'
import { Route as AdminEventRouteRouteImport } from './routes/admin/event/route'
import { Route as AdminEnquiryRouteRouteImport } from './routes/admin/enquiry/route'
import { Route as AdminCourseRouteRouteImport } from './routes/admin/course/route'
import { Route as AdminCertificateApplicationRouteRouteImport } from './routes/admin/certificate-application/route'
import { Route as AdminBrochureRouteRouteImport } from './routes/admin/brochure/route'
import { Route as AdminAudienceRouteRouteImport } from './routes/admin/audience/route'
import { Route as AdminArticleRouteRouteImport } from './routes/admin/article/route'
import { Route as AdminAlmanacRouteRouteImport } from './routes/admin/almanac/route'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminPodcastIndexRouteImport } from './routes/admin/podcast/index'
import { Route as AdminJournalIndexRouteImport } from './routes/admin/journal/index'
import { Route as AdminEventIndexRouteImport } from './routes/admin/event/index'
import { Route as AdminEnquiryIndexRouteImport } from './routes/admin/enquiry/index'
import { Route as AdminCourseIndexRouteImport } from './routes/admin/course/index'
import { Route as AdminCertificateApplicationIndexRouteImport } from './routes/admin/certificate-application/index'
import { Route as AdminBrochureIndexRouteImport } from './routes/admin/brochure/index'
import { Route as AdminAudienceIndexRouteImport } from './routes/admin/audience/index'
import { Route as AdminArticleIndexRouteImport } from './routes/admin/article/index'
import { Route as AdminAlmanacIndexRouteImport } from './routes/admin/almanac/index'
import { Route as AdminTeamFormLayoutRouteImport } from './routes/admin/team/_formLayout'
import { Route as AdminPodcastCreateRouteImport } from './routes/admin/podcast/create'
import { Route as AdminPodcastFormLayoutRouteImport } from './routes/admin/podcast/_formLayout'
import { Route as AdminPodcastIdRouteImport } from './routes/admin/podcast/$id'
import { Route as AdminJournalCreateRouteImport } from './routes/admin/journal/create'
import { Route as AdminJournalFormLayoutRouteImport } from './routes/admin/journal/_formLayout'
import { Route as AdminJournalIdRouteImport } from './routes/admin/journal/$id'
import { Route as AdminEventCreateRouteImport } from './routes/admin/event/create'
import { Route as AdminEventFormLayoutRouteImport } from './routes/admin/event/_formLayout'
import { Route as AdminEventIdRouteImport } from './routes/admin/event/$id'
import { Route as AdminEnquiryIdRouteImport } from './routes/admin/enquiry/$id'
import { Route as AdminCourseCreateRouteImport } from './routes/admin/course/create'
import { Route as AdminCourseFormLayoutRouteImport } from './routes/admin/course/_formLayout'
import { Route as AdminCourseIdRouteImport } from './routes/admin/course/$id'
import { Route as AdminBrochureCreateRouteImport } from './routes/admin/brochure/create'
import { Route as AdminBrochureFormLayoutRouteImport } from './routes/admin/brochure/_formLayout'
import { Route as AdminBrochureIdRouteImport } from './routes/admin/brochure/$id'
import { Route as AdminArticleCreateRouteImport } from './routes/admin/article/create'
import { Route as AdminArticleFormLayoutRouteImport } from './routes/admin/article/_formLayout'
import { Route as AdminArticleIdRouteImport } from './routes/admin/article/$id'
import { Route as AdminAlmanacCreateRouteImport } from './routes/admin/almanac/create'
import { Route as AdminAlmanacFormLayoutRouteImport } from './routes/admin/almanac/_formLayout'
import { Route as AdminAlmanacIdRouteImport } from './routes/admin/almanac/$id'
import { Route as AdminPodcastEditIdRouteImport } from './routes/admin/podcast/edit/$id'
import { Route as AdminJournalEditIdRouteImport } from './routes/admin/journal/edit/$id'
import { Route as AdminEventEditIdRouteImport } from './routes/admin/event/edit/$id'
import { Route as AdminCourseEnrollmentIdRouteImport } from './routes/admin/course/enrollment/$id'
import { Route as AdminCourseEditIdRouteImport } from './routes/admin/course/edit/$id'
import { Route as AdminBrochureEditIdRouteImport } from './routes/admin/brochure/edit/$id'
import { Route as AdminArticleEditIdRouteImport } from './routes/admin/article/edit/$id'
import { Route as AdminAlmanacEditIdRouteImport } from './routes/admin/almanac/edit/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamRouteRoute = AdminTeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPodcastRouteRoute = AdminPodcastRouteRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJournalRouteRoute = AdminJournalRouteRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventRouteRoute = AdminEventRouteRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiryRouteRoute = AdminEnquiryRouteRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCourseRouteRoute = AdminCourseRouteRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCertificateApplicationRouteRoute =
  AdminCertificateApplicationRouteRouteImport.update({
    id: '/certificate-application',
    path: '/certificate-application',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBrochureRouteRoute = AdminBrochureRouteRouteImport.update({
  id: '/brochure',
  path: '/brochure',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAudienceRouteRoute = AdminAudienceRouteRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticleRouteRoute = AdminArticleRouteRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlmanacRouteRoute = AdminAlmanacRouteRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTeamRouteRoute,
} as any)
const AdminPodcastIndexRoute = AdminPodcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPodcastRouteRoute,
} as any)
const AdminJournalIndexRoute = AdminJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJournalRouteRoute,
} as any)
const AdminEventIndexRoute = AdminEventIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventRouteRoute,
} as any)
const AdminEnquiryIndexRoute = AdminEnquiryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEnquiryRouteRoute,
} as any)
const AdminCourseIndexRoute = AdminCourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCourseRouteRoute,
} as any)
const AdminCertificateApplicationIndexRoute =
  AdminCertificateApplicationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCertificateApplicationRouteRoute,
  } as any)
const AdminBrochureIndexRoute = AdminBrochureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBrochureRouteRoute,
} as any)
const AdminAudienceIndexRoute = AdminAudienceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAudienceRouteRoute,
} as any)
const AdminArticleIndexRoute = AdminArticleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticleRouteRoute,
} as any)
const AdminAlmanacIndexRoute = AdminAlmanacIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAlmanacRouteRoute,
} as any)
const AdminTeamFormLayoutRoute = AdminTeamFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminTeamRouteRoute,
} as any)
const AdminPodcastCreateRoute = AdminPodcastCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminPodcastRouteRoute,
} as any)
const AdminPodcastFormLayoutRoute = AdminPodcastFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminPodcastRouteRoute,
} as any)
const AdminPodcastIdRoute = AdminPodcastIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPodcastRouteRoute,
} as any)
const AdminJournalCreateRoute = AdminJournalCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminJournalRouteRoute,
} as any)
const AdminJournalFormLayoutRoute = AdminJournalFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminJournalRouteRoute,
} as any)
const AdminJournalIdRoute = AdminJournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminJournalRouteRoute,
} as any)
const AdminEventCreateRoute = AdminEventCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminEventRouteRoute,
} as any)
const AdminEventFormLayoutRoute = AdminEventFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminEventRouteRoute,
} as any)
const AdminEventIdRoute = AdminEventIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventRouteRoute,
} as any)
const AdminEnquiryIdRoute = AdminEnquiryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEnquiryRouteRoute,
} as any)
const AdminCourseCreateRoute = AdminCourseCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminCourseRouteRoute,
} as any)
const AdminCourseFormLayoutRoute = AdminCourseFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminCourseRouteRoute,
} as any)
const AdminCourseIdRoute = AdminCourseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCourseRouteRoute,
} as any)
const AdminBrochureCreateRoute = AdminBrochureCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminBrochureRouteRoute,
} as any)
const AdminBrochureFormLayoutRoute = AdminBrochureFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminBrochureRouteRoute,
} as any)
const AdminBrochureIdRoute = AdminBrochureIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBrochureRouteRoute,
} as any)
const AdminArticleCreateRoute = AdminArticleCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminArticleRouteRoute,
} as any)
const AdminArticleFormLayoutRoute = AdminArticleFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminArticleRouteRoute,
} as any)
const AdminArticleIdRoute = AdminArticleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminArticleRouteRoute,
} as any)
const AdminAlmanacCreateRoute = AdminAlmanacCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminAlmanacRouteRoute,
} as any)
const AdminAlmanacFormLayoutRoute = AdminAlmanacFormLayoutRouteImport.update({
  id: '/_formLayout',
  getParentRoute: () => AdminAlmanacRouteRoute,
} as any)
const AdminAlmanacIdRoute = AdminAlmanacIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAlmanacRouteRoute,
} as any)
const AdminPodcastEditIdRoute = AdminPodcastEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPodcastRouteRoute,
} as any)
const AdminJournalEditIdRoute = AdminJournalEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminJournalRouteRoute,
} as any)
const AdminEventEditIdRoute = AdminEventEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminEventRouteRoute,
} as any)
const AdminCourseEnrollmentIdRoute = AdminCourseEnrollmentIdRouteImport.update({
  id: '/enrollment/$id',
  path: '/enrollment/$id',
  getParentRoute: () => AdminCourseRouteRoute,
} as any)
const AdminCourseEditIdRoute = AdminCourseEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminCourseRouteRoute,
} as any)
const AdminBrochureEditIdRoute = AdminBrochureEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminBrochureRouteRoute,
} as any)
const AdminArticleEditIdRoute = AdminArticleEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminArticleRouteRoute,
} as any)
const AdminAlmanacEditIdRoute = AdminAlmanacEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminAlmanacRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/almanac': typeof AdminAlmanacFormLayoutRoute
  '/admin/article': typeof AdminArticleFormLayoutRoute
  '/admin/audience': typeof AdminAudienceRouteRouteWithChildren
  '/admin/brochure': typeof AdminBrochureFormLayoutRoute
  '/admin/certificate-application': typeof AdminCertificateApplicationRouteRouteWithChildren
  '/admin/course': typeof AdminCourseFormLayoutRoute
  '/admin/enquiry': typeof AdminEnquiryRouteRouteWithChildren
  '/admin/event': typeof AdminEventFormLayoutRoute
  '/admin/journal': typeof AdminJournalFormLayoutRoute
  '/admin/podcast': typeof AdminPodcastFormLayoutRoute
  '/admin/team': typeof AdminTeamFormLayoutRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/almanac/$id': typeof AdminAlmanacIdRoute
  '/admin/almanac/create': typeof AdminAlmanacCreateRoute
  '/admin/article/$id': typeof AdminArticleIdRoute
  '/admin/article/create': typeof AdminArticleCreateRoute
  '/admin/brochure/$id': typeof AdminBrochureIdRoute
  '/admin/brochure/create': typeof AdminBrochureCreateRoute
  '/admin/course/$id': typeof AdminCourseIdRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/enquiry/$id': typeof AdminEnquiryIdRoute
  '/admin/event/$id': typeof AdminEventIdRoute
  '/admin/event/create': typeof AdminEventCreateRoute
  '/admin/journal/$id': typeof AdminJournalIdRoute
  '/admin/journal/create': typeof AdminJournalCreateRoute
  '/admin/podcast/$id': typeof AdminPodcastIdRoute
  '/admin/podcast/create': typeof AdminPodcastCreateRoute
  '/admin/almanac/': typeof AdminAlmanacIndexRoute
  '/admin/article/': typeof AdminArticleIndexRoute
  '/admin/audience/': typeof AdminAudienceIndexRoute
  '/admin/brochure/': typeof AdminBrochureIndexRoute
  '/admin/certificate-application/': typeof AdminCertificateApplicationIndexRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/admin/enquiry/': typeof AdminEnquiryIndexRoute
  '/admin/event/': typeof AdminEventIndexRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/podcast/': typeof AdminPodcastIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/almanac/edit/$id': typeof AdminAlmanacEditIdRoute
  '/admin/article/edit/$id': typeof AdminArticleEditIdRoute
  '/admin/brochure/edit/$id': typeof AdminBrochureEditIdRoute
  '/admin/course/edit/$id': typeof AdminCourseEditIdRoute
  '/admin/course/enrollment/$id': typeof AdminCourseEnrollmentIdRoute
  '/admin/event/edit/$id': typeof AdminEventEditIdRoute
  '/admin/journal/edit/$id': typeof AdminJournalEditIdRoute
  '/admin/podcast/edit/$id': typeof AdminPodcastEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/almanac/$id': typeof AdminAlmanacIdRoute
  '/admin/almanac': typeof AdminAlmanacIndexRoute
  '/admin/almanac/create': typeof AdminAlmanacCreateRoute
  '/admin/article/$id': typeof AdminArticleIdRoute
  '/admin/article': typeof AdminArticleIndexRoute
  '/admin/article/create': typeof AdminArticleCreateRoute
  '/admin/brochure/$id': typeof AdminBrochureIdRoute
  '/admin/brochure': typeof AdminBrochureIndexRoute
  '/admin/brochure/create': typeof AdminBrochureCreateRoute
  '/admin/course/$id': typeof AdminCourseIdRoute
  '/admin/course': typeof AdminCourseIndexRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/enquiry/$id': typeof AdminEnquiryIdRoute
  '/admin/event/$id': typeof AdminEventIdRoute
  '/admin/event': typeof AdminEventIndexRoute
  '/admin/event/create': typeof AdminEventCreateRoute
  '/admin/journal/$id': typeof AdminJournalIdRoute
  '/admin/journal': typeof AdminJournalIndexRoute
  '/admin/journal/create': typeof AdminJournalCreateRoute
  '/admin/podcast/$id': typeof AdminPodcastIdRoute
  '/admin/podcast': typeof AdminPodcastIndexRoute
  '/admin/podcast/create': typeof AdminPodcastCreateRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/admin/audience': typeof AdminAudienceIndexRoute
  '/admin/certificate-application': typeof AdminCertificateApplicationIndexRoute
  '/admin/enquiry': typeof AdminEnquiryIndexRoute
  '/admin/almanac/edit/$id': typeof AdminAlmanacEditIdRoute
  '/admin/article/edit/$id': typeof AdminArticleEditIdRoute
  '/admin/brochure/edit/$id': typeof AdminBrochureEditIdRoute
  '/admin/course/edit/$id': typeof AdminCourseEditIdRoute
  '/admin/course/enrollment/$id': typeof AdminCourseEnrollmentIdRoute
  '/admin/event/edit/$id': typeof AdminEventEditIdRoute
  '/admin/journal/edit/$id': typeof AdminJournalEditIdRoute
  '/admin/podcast/edit/$id': typeof AdminPodcastEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/almanac': typeof AdminAlmanacRouteRouteWithChildren
  '/admin/article': typeof AdminArticleRouteRouteWithChildren
  '/admin/audience': typeof AdminAudienceRouteRouteWithChildren
  '/admin/brochure': typeof AdminBrochureRouteRouteWithChildren
  '/admin/certificate-application': typeof AdminCertificateApplicationRouteRouteWithChildren
  '/admin/course': typeof AdminCourseRouteRouteWithChildren
  '/admin/enquiry': typeof AdminEnquiryRouteRouteWithChildren
  '/admin/event': typeof AdminEventRouteRouteWithChildren
  '/admin/journal': typeof AdminJournalRouteRouteWithChildren
  '/admin/podcast': typeof AdminPodcastRouteRouteWithChildren
  '/admin/team': typeof AdminTeamRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/almanac/$id': typeof AdminAlmanacIdRoute
  '/admin/almanac/_formLayout': typeof AdminAlmanacFormLayoutRoute
  '/admin/almanac/create': typeof AdminAlmanacCreateRoute
  '/admin/article/$id': typeof AdminArticleIdRoute
  '/admin/article/_formLayout': typeof AdminArticleFormLayoutRoute
  '/admin/article/create': typeof AdminArticleCreateRoute
  '/admin/brochure/$id': typeof AdminBrochureIdRoute
  '/admin/brochure/_formLayout': typeof AdminBrochureFormLayoutRoute
  '/admin/brochure/create': typeof AdminBrochureCreateRoute
  '/admin/course/$id': typeof AdminCourseIdRoute
  '/admin/course/_formLayout': typeof AdminCourseFormLayoutRoute
  '/admin/course/create': typeof AdminCourseCreateRoute
  '/admin/enquiry/$id': typeof AdminEnquiryIdRoute
  '/admin/event/$id': typeof AdminEventIdRoute
  '/admin/event/_formLayout': typeof AdminEventFormLayoutRoute
  '/admin/event/create': typeof AdminEventCreateRoute
  '/admin/journal/$id': typeof AdminJournalIdRoute
  '/admin/journal/_formLayout': typeof AdminJournalFormLayoutRoute
  '/admin/journal/create': typeof AdminJournalCreateRoute
  '/admin/podcast/$id': typeof AdminPodcastIdRoute
  '/admin/podcast/_formLayout': typeof AdminPodcastFormLayoutRoute
  '/admin/podcast/create': typeof AdminPodcastCreateRoute
  '/admin/team/_formLayout': typeof AdminTeamFormLayoutRoute
  '/admin/almanac/': typeof AdminAlmanacIndexRoute
  '/admin/article/': typeof AdminArticleIndexRoute
  '/admin/audience/': typeof AdminAudienceIndexRoute
  '/admin/brochure/': typeof AdminBrochureIndexRoute
  '/admin/certificate-application/': typeof AdminCertificateApplicationIndexRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/admin/enquiry/': typeof AdminEnquiryIndexRoute
  '/admin/event/': typeof AdminEventIndexRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/podcast/': typeof AdminPodcastIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/almanac/edit/$id': typeof AdminAlmanacEditIdRoute
  '/admin/article/edit/$id': typeof AdminArticleEditIdRoute
  '/admin/brochure/edit/$id': typeof AdminBrochureEditIdRoute
  '/admin/course/edit/$id': typeof AdminCourseEditIdRoute
  '/admin/course/enrollment/$id': typeof AdminCourseEnrollmentIdRoute
  '/admin/event/edit/$id': typeof AdminEventEditIdRoute
  '/admin/journal/edit/$id': typeof AdminJournalEditIdRoute
  '/admin/podcast/edit/$id': typeof AdminPodcastEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/almanac'
    | '/admin/article'
    | '/admin/audience'
    | '/admin/brochure'
    | '/admin/certificate-application'
    | '/admin/course'
    | '/admin/enquiry'
    | '/admin/event'
    | '/admin/journal'
    | '/admin/podcast'
    | '/admin/team'
    | '/admin/'
    | '/admin/almanac/$id'
    | '/admin/almanac/create'
    | '/admin/article/$id'
    | '/admin/article/create'
    | '/admin/brochure/$id'
    | '/admin/brochure/create'
    | '/admin/course/$id'
    | '/admin/course/create'
    | '/admin/enquiry/$id'
    | '/admin/event/$id'
    | '/admin/event/create'
    | '/admin/journal/$id'
    | '/admin/journal/create'
    | '/admin/podcast/$id'
    | '/admin/podcast/create'
    | '/admin/almanac/'
    | '/admin/article/'
    | '/admin/audience/'
    | '/admin/brochure/'
    | '/admin/certificate-application/'
    | '/admin/course/'
    | '/admin/enquiry/'
    | '/admin/event/'
    | '/admin/journal/'
    | '/admin/podcast/'
    | '/admin/team/'
    | '/admin/almanac/edit/$id'
    | '/admin/article/edit/$id'
    | '/admin/brochure/edit/$id'
    | '/admin/course/edit/$id'
    | '/admin/course/enrollment/$id'
    | '/admin/event/edit/$id'
    | '/admin/journal/edit/$id'
    | '/admin/podcast/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/almanac/$id'
    | '/admin/almanac'
    | '/admin/almanac/create'
    | '/admin/article/$id'
    | '/admin/article'
    | '/admin/article/create'
    | '/admin/brochure/$id'
    | '/admin/brochure'
    | '/admin/brochure/create'
    | '/admin/course/$id'
    | '/admin/course'
    | '/admin/course/create'
    | '/admin/enquiry/$id'
    | '/admin/event/$id'
    | '/admin/event'
    | '/admin/event/create'
    | '/admin/journal/$id'
    | '/admin/journal'
    | '/admin/journal/create'
    | '/admin/podcast/$id'
    | '/admin/podcast'
    | '/admin/podcast/create'
    | '/admin/team'
    | '/admin/audience'
    | '/admin/certificate-application'
    | '/admin/enquiry'
    | '/admin/almanac/edit/$id'
    | '/admin/article/edit/$id'
    | '/admin/brochure/edit/$id'
    | '/admin/course/edit/$id'
    | '/admin/course/enrollment/$id'
    | '/admin/event/edit/$id'
    | '/admin/journal/edit/$id'
    | '/admin/podcast/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/almanac'
    | '/admin/article'
    | '/admin/audience'
    | '/admin/brochure'
    | '/admin/certificate-application'
    | '/admin/course'
    | '/admin/enquiry'
    | '/admin/event'
    | '/admin/journal'
    | '/admin/podcast'
    | '/admin/team'
    | '/admin/'
    | '/admin/almanac/$id'
    | '/admin/almanac/_formLayout'
    | '/admin/almanac/create'
    | '/admin/article/$id'
    | '/admin/article/_formLayout'
    | '/admin/article/create'
    | '/admin/brochure/$id'
    | '/admin/brochure/_formLayout'
    | '/admin/brochure/create'
    | '/admin/course/$id'
    | '/admin/course/_formLayout'
    | '/admin/course/create'
    | '/admin/enquiry/$id'
    | '/admin/event/$id'
    | '/admin/event/_formLayout'
    | '/admin/event/create'
    | '/admin/journal/$id'
    | '/admin/journal/_formLayout'
    | '/admin/journal/create'
    | '/admin/podcast/$id'
    | '/admin/podcast/_formLayout'
    | '/admin/podcast/create'
    | '/admin/team/_formLayout'
    | '/admin/almanac/'
    | '/admin/article/'
    | '/admin/audience/'
    | '/admin/brochure/'
    | '/admin/certificate-application/'
    | '/admin/course/'
    | '/admin/enquiry/'
    | '/admin/event/'
    | '/admin/journal/'
    | '/admin/podcast/'
    | '/admin/team/'
    | '/admin/almanac/edit/$id'
    | '/admin/article/edit/$id'
    | '/admin/brochure/edit/$id'
    | '/admin/course/edit/$id'
    | '/admin/course/enrollment/$id'
    | '/admin/event/edit/$id'
    | '/admin/journal/edit/$id'
    | '/admin/podcast/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/podcast': {
      id: '/admin/podcast'
      path: '/podcast'
      fullPath: '/admin/podcast'
      preLoaderRoute: typeof AdminPodcastRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/journal': {
      id: '/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/event': {
      id: '/admin/event'
      path: '/event'
      fullPath: '/admin/event'
      preLoaderRoute: typeof AdminEventRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiry': {
      id: '/admin/enquiry'
      path: '/enquiry'
      fullPath: '/admin/enquiry'
      preLoaderRoute: typeof AdminEnquiryRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/course': {
      id: '/admin/course'
      path: '/course'
      fullPath: '/admin/course'
      preLoaderRoute: typeof AdminCourseRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/certificate-application': {
      id: '/admin/certificate-application'
      path: '/certificate-application'
      fullPath: '/admin/certificate-application'
      preLoaderRoute: typeof AdminCertificateApplicationRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brochure': {
      id: '/admin/brochure'
      path: '/brochure'
      fullPath: '/admin/brochure'
      preLoaderRoute: typeof AdminBrochureRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audience': {
      id: '/admin/audience'
      path: '/audience'
      fullPath: '/admin/audience'
      preLoaderRoute: typeof AdminAudienceRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/article': {
      id: '/admin/article'
      path: '/article'
      fullPath: '/admin/article'
      preLoaderRoute: typeof AdminArticleRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/almanac': {
      id: '/admin/almanac'
      path: '/almanac'
      fullPath: '/admin/almanac'
      preLoaderRoute: typeof AdminAlmanacRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/'
      fullPath: '/admin/team/'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof AdminTeamRouteRoute
    }
    '/admin/podcast/': {
      id: '/admin/podcast/'
      path: '/'
      fullPath: '/admin/podcast/'
      preLoaderRoute: typeof AdminPodcastIndexRouteImport
      parentRoute: typeof AdminPodcastRouteRoute
    }
    '/admin/journal/': {
      id: '/admin/journal/'
      path: '/'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AdminJournalIndexRouteImport
      parentRoute: typeof AdminJournalRouteRoute
    }
    '/admin/event/': {
      id: '/admin/event/'
      path: '/'
      fullPath: '/admin/event/'
      preLoaderRoute: typeof AdminEventIndexRouteImport
      parentRoute: typeof AdminEventRouteRoute
    }
    '/admin/enquiry/': {
      id: '/admin/enquiry/'
      path: '/'
      fullPath: '/admin/enquiry/'
      preLoaderRoute: typeof AdminEnquiryIndexRouteImport
      parentRoute: typeof AdminEnquiryRouteRoute
    }
    '/admin/course/': {
      id: '/admin/course/'
      path: '/'
      fullPath: '/admin/course/'
      preLoaderRoute: typeof AdminCourseIndexRouteImport
      parentRoute: typeof AdminCourseRouteRoute
    }
    '/admin/certificate-application/': {
      id: '/admin/certificate-application/'
      path: '/'
      fullPath: '/admin/certificate-application/'
      preLoaderRoute: typeof AdminCertificateApplicationIndexRouteImport
      parentRoute: typeof AdminCertificateApplicationRouteRoute
    }
    '/admin/brochure/': {
      id: '/admin/brochure/'
      path: '/'
      fullPath: '/admin/brochure/'
      preLoaderRoute: typeof AdminBrochureIndexRouteImport
      parentRoute: typeof AdminBrochureRouteRoute
    }
    '/admin/audience/': {
      id: '/admin/audience/'
      path: '/'
      fullPath: '/admin/audience/'
      preLoaderRoute: typeof AdminAudienceIndexRouteImport
      parentRoute: typeof AdminAudienceRouteRoute
    }
    '/admin/article/': {
      id: '/admin/article/'
      path: '/'
      fullPath: '/admin/article/'
      preLoaderRoute: typeof AdminArticleIndexRouteImport
      parentRoute: typeof AdminArticleRouteRoute
    }
    '/admin/almanac/': {
      id: '/admin/almanac/'
      path: '/'
      fullPath: '/admin/almanac/'
      preLoaderRoute: typeof AdminAlmanacIndexRouteImport
      parentRoute: typeof AdminAlmanacRouteRoute
    }
    '/admin/team/_formLayout': {
      id: '/admin/team/_formLayout'
      path: ''
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamFormLayoutRouteImport
      parentRoute: typeof AdminTeamRouteRoute
    }
    '/admin/podcast/create': {
      id: '/admin/podcast/create'
      path: '/create'
      fullPath: '/admin/podcast/create'
      preLoaderRoute: typeof AdminPodcastCreateRouteImport
      parentRoute: typeof AdminPodcastRouteRoute
    }
    '/admin/podcast/_formLayout': {
      id: '/admin/podcast/_formLayout'
      path: ''
      fullPath: '/admin/podcast'
      preLoaderRoute: typeof AdminPodcastFormLayoutRouteImport
      parentRoute: typeof AdminPodcastRouteRoute
    }
    '/admin/podcast/$id': {
      id: '/admin/podcast/$id'
      path: '/$id'
      fullPath: '/admin/podcast/$id'
      preLoaderRoute: typeof AdminPodcastIdRouteImport
      parentRoute: typeof AdminPodcastRouteRoute
    }
    '/admin/journal/create': {
      id: '/admin/journal/create'
      path: '/create'
      fullPath: '/admin/journal/create'
      preLoaderRoute: typeof AdminJournalCreateRouteImport
      parentRoute: typeof AdminJournalRouteRoute
    }
    '/admin/journal/_formLayout': {
      id: '/admin/journal/_formLayout'
      path: ''
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalFormLayoutRouteImport
      parentRoute: typeof AdminJournalRouteRoute
    }
    '/admin/journal/$id': {
      id: '/admin/journal/$id'
      path: '/$id'
      fullPath: '/admin/journal/$id'
      preLoaderRoute: typeof AdminJournalIdRouteImport
      parentRoute: typeof AdminJournalRouteRoute
    }
    '/admin/event/create': {
      id: '/admin/event/create'
      path: '/create'
      fullPath: '/admin/event/create'
      preLoaderRoute: typeof AdminEventCreateRouteImport
      parentRoute: typeof AdminEventRouteRoute
    }
    '/admin/event/_formLayout': {
      id: '/admin/event/_formLayout'
      path: ''
      fullPath: '/admin/event'
      preLoaderRoute: typeof AdminEventFormLayoutRouteImport
      parentRoute: typeof AdminEventRouteRoute
    }
    '/admin/event/$id': {
      id: '/admin/event/$id'
      path: '/$id'
      fullPath: '/admin/event/$id'
      preLoaderRoute: typeof AdminEventIdRouteImport
      parentRoute: typeof AdminEventRouteRoute
    }
    '/admin/enquiry/$id': {
      id: '/admin/enquiry/$id'
      path: '/$id'
      fullPath: '/admin/enquiry/$id'
      preLoaderRoute: typeof AdminEnquiryIdRouteImport
      parentRoute: typeof AdminEnquiryRouteRoute
    }
    '/admin/course/create': {
      id: '/admin/course/create'
      path: '/create'
      fullPath: '/admin/course/create'
      preLoaderRoute: typeof AdminCourseCreateRouteImport
      parentRoute: typeof AdminCourseRouteRoute
    }
    '/admin/course/_formLayout': {
      id: '/admin/course/_formLayout'
      path: ''
      fullPath: '/admin/course'
      preLoaderRoute: typeof AdminCourseFormLayoutRouteImport
      parentRoute: typeof AdminCourseRouteRoute
    }
    '/admin/course/$id': {
      id: '/admin/course/$id'
      path: '/$id'
      fullPath: '/admin/course/$id'
      preLoaderRoute: typeof AdminCourseIdRouteImport
      parentRoute: typeof AdminCourseRouteRoute
    }
    '/admin/brochure/create': {
      id: '/admin/brochure/create'
      path: '/create'
      fullPath: '/admin/brochure/create'
      preLoaderRoute: typeof AdminBrochureCreateRouteImport
      parentRoute: typeof AdminBrochureRouteRoute
    }
    '/admin/brochure/_formLayout': {
      id: '/admin/brochure/_formLayout'
      path: ''
      fullPath: '/admin/brochure'
      preLoaderRoute: typeof AdminBrochureFormLayoutRouteImport
      parentRoute: typeof AdminBrochureRouteRoute
    }
    '/admin/brochure/$id': {
      id: '/admin/brochure/$id'
      path: '/$id'
      fullPath: '/admin/brochure/$id'
      preLoaderRoute: typeof AdminBrochureIdRouteImport
      parentRoute: typeof AdminBrochureRouteRoute
    }
    '/admin/article/create': {
      id: '/admin/article/create'
      path: '/create'
      fullPath: '/admin/article/create'
      preLoaderRoute: typeof AdminArticleCreateRouteImport
      parentRoute: typeof AdminArticleRouteRoute
    }
    '/admin/article/_formLayout': {
      id: '/admin/article/_formLayout'
      path: ''
      fullPath: '/admin/article'
      preLoaderRoute: typeof AdminArticleFormLayoutRouteImport
      parentRoute: typeof AdminArticleRouteRoute
    }
    '/admin/article/$id': {
      id: '/admin/article/$id'
      path: '/$id'
      fullPath: '/admin/article/$id'
      preLoaderRoute: typeof AdminArticleIdRouteImport
      parentRoute: typeof AdminArticleRouteRoute
    }
    '/admin/almanac/create': {
      id: '/admin/almanac/create'
      path: '/create'
      fullPath: '/admin/almanac/create'
      preLoaderRoute: typeof AdminAlmanacCreateRouteImport
      parentRoute: typeof AdminAlmanacRouteRoute
    }
    '/admin/almanac/_formLayout': {
      id: '/admin/almanac/_formLayout'
      path: ''
      fullPath: '/admin/almanac'
      preLoaderRoute: typeof AdminAlmanacFormLayoutRouteImport
      parentRoute: typeof AdminAlmanacRouteRoute
    }
    '/admin/almanac/$id': {
      id: '/admin/almanac/$id'
      path: '/$id'
      fullPath: '/admin/almanac/$id'
      preLoaderRoute: typeof AdminAlmanacIdRouteImport
      parentRoute: typeof AdminAlmanacRouteRoute
    }
    '/admin/podcast/edit/$id': {
      id: '/admin/podcast/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/podcast/edit/$id'
      preLoaderRoute: typeof AdminPodcastEditIdRouteImport
      parentRoute: typeof AdminPodcastRouteRoute
    }
    '/admin/journal/edit/$id': {
      id: '/admin/journal/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/journal/edit/$id'
      preLoaderRoute: typeof AdminJournalEditIdRouteImport
      parentRoute: typeof AdminJournalRouteRoute
    }
    '/admin/event/edit/$id': {
      id: '/admin/event/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/event/edit/$id'
      preLoaderRoute: typeof AdminEventEditIdRouteImport
      parentRoute: typeof AdminEventRouteRoute
    }
    '/admin/course/enrollment/$id': {
      id: '/admin/course/enrollment/$id'
      path: '/enrollment/$id'
      fullPath: '/admin/course/enrollment/$id'
      preLoaderRoute: typeof AdminCourseEnrollmentIdRouteImport
      parentRoute: typeof AdminCourseRouteRoute
    }
    '/admin/course/edit/$id': {
      id: '/admin/course/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/course/edit/$id'
      preLoaderRoute: typeof AdminCourseEditIdRouteImport
      parentRoute: typeof AdminCourseRouteRoute
    }
    '/admin/brochure/edit/$id': {
      id: '/admin/brochure/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/brochure/edit/$id'
      preLoaderRoute: typeof AdminBrochureEditIdRouteImport
      parentRoute: typeof AdminBrochureRouteRoute
    }
    '/admin/article/edit/$id': {
      id: '/admin/article/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/article/edit/$id'
      preLoaderRoute: typeof AdminArticleEditIdRouteImport
      parentRoute: typeof AdminArticleRouteRoute
    }
    '/admin/almanac/edit/$id': {
      id: '/admin/almanac/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/almanac/edit/$id'
      preLoaderRoute: typeof AdminAlmanacEditIdRouteImport
      parentRoute: typeof AdminAlmanacRouteRoute
    }
  }
}

interface AdminAlmanacRouteRouteChildren {
  AdminAlmanacIdRoute: typeof AdminAlmanacIdRoute
  AdminAlmanacFormLayoutRoute: typeof AdminAlmanacFormLayoutRoute
  AdminAlmanacCreateRoute: typeof AdminAlmanacCreateRoute
  AdminAlmanacIndexRoute: typeof AdminAlmanacIndexRoute
  AdminAlmanacEditIdRoute: typeof AdminAlmanacEditIdRoute
}

const AdminAlmanacRouteRouteChildren: AdminAlmanacRouteRouteChildren = {
  AdminAlmanacIdRoute: AdminAlmanacIdRoute,
  AdminAlmanacFormLayoutRoute: AdminAlmanacFormLayoutRoute,
  AdminAlmanacCreateRoute: AdminAlmanacCreateRoute,
  AdminAlmanacIndexRoute: AdminAlmanacIndexRoute,
  AdminAlmanacEditIdRoute: AdminAlmanacEditIdRoute,
}

const AdminAlmanacRouteRouteWithChildren =
  AdminAlmanacRouteRoute._addFileChildren(AdminAlmanacRouteRouteChildren)

interface AdminArticleRouteRouteChildren {
  AdminArticleIdRoute: typeof AdminArticleIdRoute
  AdminArticleFormLayoutRoute: typeof AdminArticleFormLayoutRoute
  AdminArticleCreateRoute: typeof AdminArticleCreateRoute
  AdminArticleIndexRoute: typeof AdminArticleIndexRoute
  AdminArticleEditIdRoute: typeof AdminArticleEditIdRoute
}

const AdminArticleRouteRouteChildren: AdminArticleRouteRouteChildren = {
  AdminArticleIdRoute: AdminArticleIdRoute,
  AdminArticleFormLayoutRoute: AdminArticleFormLayoutRoute,
  AdminArticleCreateRoute: AdminArticleCreateRoute,
  AdminArticleIndexRoute: AdminArticleIndexRoute,
  AdminArticleEditIdRoute: AdminArticleEditIdRoute,
}

const AdminArticleRouteRouteWithChildren =
  AdminArticleRouteRoute._addFileChildren(AdminArticleRouteRouteChildren)

interface AdminAudienceRouteRouteChildren {
  AdminAudienceIndexRoute: typeof AdminAudienceIndexRoute
}

const AdminAudienceRouteRouteChildren: AdminAudienceRouteRouteChildren = {
  AdminAudienceIndexRoute: AdminAudienceIndexRoute,
}

const AdminAudienceRouteRouteWithChildren =
  AdminAudienceRouteRoute._addFileChildren(AdminAudienceRouteRouteChildren)

interface AdminBrochureRouteRouteChildren {
  AdminBrochureIdRoute: typeof AdminBrochureIdRoute
  AdminBrochureFormLayoutRoute: typeof AdminBrochureFormLayoutRoute
  AdminBrochureCreateRoute: typeof AdminBrochureCreateRoute
  AdminBrochureIndexRoute: typeof AdminBrochureIndexRoute
  AdminBrochureEditIdRoute: typeof AdminBrochureEditIdRoute
}

const AdminBrochureRouteRouteChildren: AdminBrochureRouteRouteChildren = {
  AdminBrochureIdRoute: AdminBrochureIdRoute,
  AdminBrochureFormLayoutRoute: AdminBrochureFormLayoutRoute,
  AdminBrochureCreateRoute: AdminBrochureCreateRoute,
  AdminBrochureIndexRoute: AdminBrochureIndexRoute,
  AdminBrochureEditIdRoute: AdminBrochureEditIdRoute,
}

const AdminBrochureRouteRouteWithChildren =
  AdminBrochureRouteRoute._addFileChildren(AdminBrochureRouteRouteChildren)

interface AdminCertificateApplicationRouteRouteChildren {
  AdminCertificateApplicationIndexRoute: typeof AdminCertificateApplicationIndexRoute
}

const AdminCertificateApplicationRouteRouteChildren: AdminCertificateApplicationRouteRouteChildren =
  {
    AdminCertificateApplicationIndexRoute:
      AdminCertificateApplicationIndexRoute,
  }

const AdminCertificateApplicationRouteRouteWithChildren =
  AdminCertificateApplicationRouteRoute._addFileChildren(
    AdminCertificateApplicationRouteRouteChildren,
  )

interface AdminCourseRouteRouteChildren {
  AdminCourseIdRoute: typeof AdminCourseIdRoute
  AdminCourseFormLayoutRoute: typeof AdminCourseFormLayoutRoute
  AdminCourseCreateRoute: typeof AdminCourseCreateRoute
  AdminCourseIndexRoute: typeof AdminCourseIndexRoute
  AdminCourseEditIdRoute: typeof AdminCourseEditIdRoute
  AdminCourseEnrollmentIdRoute: typeof AdminCourseEnrollmentIdRoute
}

const AdminCourseRouteRouteChildren: AdminCourseRouteRouteChildren = {
  AdminCourseIdRoute: AdminCourseIdRoute,
  AdminCourseFormLayoutRoute: AdminCourseFormLayoutRoute,
  AdminCourseCreateRoute: AdminCourseCreateRoute,
  AdminCourseIndexRoute: AdminCourseIndexRoute,
  AdminCourseEditIdRoute: AdminCourseEditIdRoute,
  AdminCourseEnrollmentIdRoute: AdminCourseEnrollmentIdRoute,
}

const AdminCourseRouteRouteWithChildren =
  AdminCourseRouteRoute._addFileChildren(AdminCourseRouteRouteChildren)

interface AdminEnquiryRouteRouteChildren {
  AdminEnquiryIdRoute: typeof AdminEnquiryIdRoute
  AdminEnquiryIndexRoute: typeof AdminEnquiryIndexRoute
}

const AdminEnquiryRouteRouteChildren: AdminEnquiryRouteRouteChildren = {
  AdminEnquiryIdRoute: AdminEnquiryIdRoute,
  AdminEnquiryIndexRoute: AdminEnquiryIndexRoute,
}

const AdminEnquiryRouteRouteWithChildren =
  AdminEnquiryRouteRoute._addFileChildren(AdminEnquiryRouteRouteChildren)

interface AdminEventRouteRouteChildren {
  AdminEventIdRoute: typeof AdminEventIdRoute
  AdminEventFormLayoutRoute: typeof AdminEventFormLayoutRoute
  AdminEventCreateRoute: typeof AdminEventCreateRoute
  AdminEventIndexRoute: typeof AdminEventIndexRoute
  AdminEventEditIdRoute: typeof AdminEventEditIdRoute
}

const AdminEventRouteRouteChildren: AdminEventRouteRouteChildren = {
  AdminEventIdRoute: AdminEventIdRoute,
  AdminEventFormLayoutRoute: AdminEventFormLayoutRoute,
  AdminEventCreateRoute: AdminEventCreateRoute,
  AdminEventIndexRoute: AdminEventIndexRoute,
  AdminEventEditIdRoute: AdminEventEditIdRoute,
}

const AdminEventRouteRouteWithChildren = AdminEventRouteRoute._addFileChildren(
  AdminEventRouteRouteChildren,
)

interface AdminJournalRouteRouteChildren {
  AdminJournalIdRoute: typeof AdminJournalIdRoute
  AdminJournalFormLayoutRoute: typeof AdminJournalFormLayoutRoute
  AdminJournalCreateRoute: typeof AdminJournalCreateRoute
  AdminJournalIndexRoute: typeof AdminJournalIndexRoute
  AdminJournalEditIdRoute: typeof AdminJournalEditIdRoute
}

const AdminJournalRouteRouteChildren: AdminJournalRouteRouteChildren = {
  AdminJournalIdRoute: AdminJournalIdRoute,
  AdminJournalFormLayoutRoute: AdminJournalFormLayoutRoute,
  AdminJournalCreateRoute: AdminJournalCreateRoute,
  AdminJournalIndexRoute: AdminJournalIndexRoute,
  AdminJournalEditIdRoute: AdminJournalEditIdRoute,
}

const AdminJournalRouteRouteWithChildren =
  AdminJournalRouteRoute._addFileChildren(AdminJournalRouteRouteChildren)

interface AdminPodcastRouteRouteChildren {
  AdminPodcastIdRoute: typeof AdminPodcastIdRoute
  AdminPodcastFormLayoutRoute: typeof AdminPodcastFormLayoutRoute
  AdminPodcastCreateRoute: typeof AdminPodcastCreateRoute
  AdminPodcastIndexRoute: typeof AdminPodcastIndexRoute
  AdminPodcastEditIdRoute: typeof AdminPodcastEditIdRoute
}

const AdminPodcastRouteRouteChildren: AdminPodcastRouteRouteChildren = {
  AdminPodcastIdRoute: AdminPodcastIdRoute,
  AdminPodcastFormLayoutRoute: AdminPodcastFormLayoutRoute,
  AdminPodcastCreateRoute: AdminPodcastCreateRoute,
  AdminPodcastIndexRoute: AdminPodcastIndexRoute,
  AdminPodcastEditIdRoute: AdminPodcastEditIdRoute,
}

const AdminPodcastRouteRouteWithChildren =
  AdminPodcastRouteRoute._addFileChildren(AdminPodcastRouteRouteChildren)

interface AdminTeamRouteRouteChildren {
  AdminTeamFormLayoutRoute: typeof AdminTeamFormLayoutRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
}

const AdminTeamRouteRouteChildren: AdminTeamRouteRouteChildren = {
  AdminTeamFormLayoutRoute: AdminTeamFormLayoutRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
}

const AdminTeamRouteRouteWithChildren = AdminTeamRouteRoute._addFileChildren(
  AdminTeamRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAlmanacRouteRoute: typeof AdminAlmanacRouteRouteWithChildren
  AdminArticleRouteRoute: typeof AdminArticleRouteRouteWithChildren
  AdminAudienceRouteRoute: typeof AdminAudienceRouteRouteWithChildren
  AdminBrochureRouteRoute: typeof AdminBrochureRouteRouteWithChildren
  AdminCertificateApplicationRouteRoute: typeof AdminCertificateApplicationRouteRouteWithChildren
  AdminCourseRouteRoute: typeof AdminCourseRouteRouteWithChildren
  AdminEnquiryRouteRoute: typeof AdminEnquiryRouteRouteWithChildren
  AdminEventRouteRoute: typeof AdminEventRouteRouteWithChildren
  AdminJournalRouteRoute: typeof AdminJournalRouteRouteWithChildren
  AdminPodcastRouteRoute: typeof AdminPodcastRouteRouteWithChildren
  AdminTeamRouteRoute: typeof AdminTeamRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAlmanacRouteRoute: AdminAlmanacRouteRouteWithChildren,
  AdminArticleRouteRoute: AdminArticleRouteRouteWithChildren,
  AdminAudienceRouteRoute: AdminAudienceRouteRouteWithChildren,
  AdminBrochureRouteRoute: AdminBrochureRouteRouteWithChildren,
  AdminCertificateApplicationRouteRoute:
    AdminCertificateApplicationRouteRouteWithChildren,
  AdminCourseRouteRoute: AdminCourseRouteRouteWithChildren,
  AdminEnquiryRouteRoute: AdminEnquiryRouteRouteWithChildren,
  AdminEventRouteRoute: AdminEventRouteRouteWithChildren,
  AdminJournalRouteRoute: AdminJournalRouteRouteWithChildren,
  AdminPodcastRouteRoute: AdminPodcastRouteRouteWithChildren,
  AdminTeamRouteRoute: AdminTeamRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
